### ISSUE TITLE
Update 2 Checklist

### ISSUE THREAD

**Issue by NorbiPeti** [TBMCPlugins/DiscordPlugin#52]
- [ ] Fix first command (mcchat?) not working in DMs
- [x] Fix command handling (empty args)
- [x] Automatically detect game roles
- [x] Add support for channel commands
- [x] Post Tableflips and other chat commands when ran from Discord
- [ ] Add Discord to the list of broadcasts even if nobody has talked from Discord
- [x] Fix DiscordSender hover info
  - [ ] Add and use CGBase instead of CommandSender in TBMCChatEvent, so getInfo can get called from Discord
- [x] Convert emojis to text from Discord
- [x] Channel connection with any MC and Discord channel
- [x] Showing help text for commands when used wrong
- [x] Add `/` as Discord command prefix

**Comment by NorbiPeti** [comment]
https://github.com/TBMCPlugins/DiscordPlugin/commit/b8814030e2be7d002daff13700df6fb920d67724
